In [44]:
import numpy as np
import pandas as pd

In [45]:

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [22, 25, 30],
    "City": ["NY", "LA", "Chicago"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Alice   22       NY
1      Bob   25       LA
2  Charlie   30  Chicago

Split->Split the DataFrame into groups.
Aplly->Perform an operation on each group.
Combine->Combine the results into a new object.

In [46]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["IT", "HR", "IT", "HR", "IT"],
    "Salary": [70000, 50000, 90000, 55000, 80000],
    "Age": [22, 25, 30, 28, 35]
})

print(df2)

      Name Department  Salary  Age
0    Alice         IT   70000   22
1      Bob         HR   50000   25
2  Charlie         IT   90000   30
3    David         HR   55000   28
4      Eva         IT   80000   35

In [47]:
#group by department or split by department 
groups = df2.groupby("Department")
print(groups)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x10e998860>

In [48]:
# Apply any operation on it  and combine it 
df2.groupby("Department")["Salary"].mean()

Department
HR    52500.0
IT    80000.0
Name: Salary, dtype: float64

Aggregate Multiple Coloumn With Multiple Function(Grouped)

In [49]:
result = df2.groupby("Department").agg({
    "Salary": ["sum", "mean", "max"],
    "Age": ["min", "max", "mean"]
})

result

            Salary                 Age
               sum     mean    max min max  mean
Department
HR          105000  52500.0  55000  25  28  26.5
IT          240000  80000.0  90000  22  35  29.0


merge()	-> Combine DataFrames based on common columns or keys--JOIN
concat() -> Stack DataFrames vertically or horizontally. --	UNION / column binding
join()	-> Join DataFrames using their indexes (or a key) --	JOIN

In [50]:
df3 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"]
})

df4 = pd.DataFrame({
    "ID": [1, 2, 4],
    "Salary": [50000, 60000, 70000]
})

result = pd.merge(df3, df4, on="ID", how="inner")
print(result)

   ID   Name  Salary
0   1  Alice   50000
1   2    Bob   60000

Merge Types

In [51]:
pd.merge(df3, df4, on="ID", how="inner")   # Common rows
pd.merge(df3, df4, on="ID", how="left")    # All rows from left
pd.merge(df3, df4, on="ID", how="right")   # All rows from right
pd.merge(df3, df4, on="ID", how="outer")   # All rows from both

   ID     Name   Salary
0   1    Alice  50000.0
1   2      Bob  60000.0
2   3  Charlie      NaN
3   4      NaN  70000.0

In [52]:
df5 = pd.DataFrame({
    "Date": [
        "2024-01-01", "2024-01-02", "2024-01-03", "2024-01-04",
        "2024-01-05", "2024-01-06", "2024-01-07", "2024-01-08",
        "2024-01-09", "2024-01-10"
    ],
    "Product": [
        "Laptop", "Phone", "Tablet", "Monitor", "Keyboard",
        "Mouse", "Laptop", "Phone", "Tablet", "Monitor"
    ],
    "Region": [
        "North", "South", "East", "West", "North",
        "South", "East", "West", "North", "South"
    ],
    "Sales": [
        1200, 800, 600, 450, 150,
        100, 1800, 950, 700, 550
    ],
    "Units": [
        2, 4, 3, 5, 10,
        12, 3, 5, 4, 6
    ],
    "Rep": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan",
        "Alice", "Bob", "Charlie", "Diana", "Ethan"
    ]
})


print(df5)

         Date   Product Region  Sales  Units      Rep
0  2024-01-01    Laptop  North   1200      2    Alice
1  2024-01-02     Phone  South    800      4      Bob
2  2024-01-03    Tablet   East    600      3  Charlie
3  2024-01-04   Monitor   West    450      5    Diana
4  2024-01-05  Keyboard  North    150     10    Ethan
5  2024-01-06     Mouse  South    100     12    Alice
6  2024-01-07    Laptop   East   1800      3      Bob
7  2024-01-08     Phone   West    950      5  Charlie
8  2024-01-09    Tablet  North    700      4    Diana
9  2024-01-10   Monitor  South    550      6    Ethan

In [53]:
from datetime import datetime

In [54]:
date=[datetime(2020,1,5),
      datetime(2020,1,10),
      datetime(2020,1,15),
      datetime(2020,1,20),
      datetime(2020,1,25)]
date

[datetime.datetime(2020, 1, 5, 0, 0),
 datetime.datetime(2020, 1, 10, 0, 0),
 datetime.datetime(2020, 1, 15, 0, 0),
 datetime.datetime(2020, 1, 20, 0, 0),
 datetime.datetime(2020, 1, 25, 0, 0)]

In [55]:
ts=pd.Series(np.random.rand(5),index=date)
ts

2020-01-05    0.654144
2020-01-10    0.311201
2020-01-15    0.475290
2020-01-20    0.010382
2020-01-25    0.989812
dtype: float64

In [56]:
ts.index

DatetimeIndex(['2020-01-05', '2020-01-10', '2020-01-15', '2020-01-20',
               '2020-01-25'],
              dtype='datetime64[ns]', freq=None)

In [57]:
pd.to_datetime("01/01/2020")

Timestamp('2020-01-01 00:00:00')

In [58]:
dates=pd.to_datetime(
    [datetime(2020,7,5),
     "6th of July, 2020",
     "2020-Jul-7",
     "20200708"])
dates

DatetimeIndex(['2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08'], dtype='datetime64[ns]', freq=None)

In [59]:
dates.to_period("D")

PeriodIndex(['2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08'], dtype='period[D]')

In [60]:
dates-dates[0]

TimedeltaIndex(['0 days', '1 days', '2 days', '3 days'], dtype='timedelta64[ns]', freq=None)

In [61]:
pd.date_range("2020-08-15","2020-09-01")

DatetimeIndex(['2020-08-15', '2020-08-16', '2020-08-17', '2020-08-18',
               '2020-08-19', '2020-08-20', '2020-08-21', '2020-08-22',
               '2020-08-23', '2020-08-24', '2020-08-25', '2020-08-26',
               '2020-08-27', '2020-08-28', '2020-08-29', '2020-08-30',
               '2020-08-31', '2020-09-01'],
              dtype='datetime64[ns]', freq='D')

In [62]:
pd.date_range('2020-07-15',periods=10)

DatetimeIndex(['2020-07-15', '2020-07-16', '2020-07-17', '2020-07-18',
               '2020-07-19', '2020-07-20', '2020-07-21', '2020-07-22',
               '2020-07-23', '2020-07-24'],
              dtype='datetime64[ns]', freq='D')

In [63]:
pd.date_range("2020-07-15",periods=10,freq="H")

/var/folders/h4/9ytflx8j06v6w6t3cpsjkj7m0000gn/T/ipykernel_88201/495874734.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range("2020-07-15",periods=10,freq="H")

DatetimeIndex(['2020-07-15 00:00:00', '2020-07-15 01:00:00',
               '2020-07-15 02:00:00', '2020-07-15 03:00:00',
               '2020-07-15 04:00:00', '2020-07-15 05:00:00',
               '2020-07-15 06:00:00', '2020-07-15 07:00:00',
               '2020-07-15 08:00:00', '2020-07-15 09:00:00'],
              dtype='datetime64[ns]', freq='h')

In [64]:
pd.period_range("2020-10",periods=10,freq="M")

PeriodIndex(['2020-10', '2020-11', '2020-12', '2021-01', '2021-02', '2021-03',
             '2021-04', '2021-05', '2021-06', '2021-07'],
            dtype='period[M]')

In [65]:
pd.timedelta_range(0,periods=8,freq="H")

/var/folders/h4/9ytflx8j06v6w6t3cpsjkj7m0000gn/T/ipykernel_88201/3215923703.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.timedelta_range(0,periods=8,freq="H")

TimedeltaIndex(['0 days 00:00:00', '0 days 01:00:00', '0 days 02:00:00',
                '0 days 03:00:00', '0 days 04:00:00', '0 days 05:00:00',
                '0 days 06:00:00', '0 days 07:00:00'],
               dtype='timedelta64[ns]', freq='h')

In [66]:
stamp=ts.index[1]
stamp

Timestamp('2020-01-10 00:00:00')

In [67]:
ts[stamp]

np.float64(0.31120089688169017)

In [68]:
ts["25.1.2020"]
ts["20200125"]

np.float64(0.9898120821561097)

In [69]:
long_ts=pd.Series(
    np.random.randn(1000),
    index=pd.date_range("1/1/2020",periods=1000))
long_ts.head()

2020-01-01   -1.131714
2020-01-02    1.958949
2020-01-03   -0.225302
2020-01-04    0.926124
2020-01-05   -0.547136
Freq: D, dtype: float64

In [70]:
long_ts["2020"].head()
long_ts["2020-10"].head(15)
long_ts[datetime(2022,9,20):datetime(2022,9,27)]

2022-09-20   -0.662370
2022-09-21   -1.056131
2022-09-22    1.858930
2022-09-23    2.090574
2022-09-24    0.113327
2022-09-25   -0.053108
2022-09-26   -1.586837
Freq: D, dtype: float64