In [1]:
import numpy as np
import pandas as pd

In [2]:

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [22, 25, 30],
    "City": ["NY", "LA", "Chicago"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Alice   22       NY
1      Bob   25       LA
2  Charlie   30  Chicago

Split->Split the DataFrame into groups.
Aplly->Perform an operation on each group.
Combine->Combine the results into a new object.

In [12]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["IT", "HR", "IT", "HR", "IT"],
    "Salary": [70000, 50000, 90000, 55000, 80000],
    "Age": [22, 25, 30, 28, 35]
})

print(df2)

      Name Department  Salary  Age
0    Alice         IT   70000   22
1      Bob         HR   50000   25
2  Charlie         IT   90000   30
3    David         HR   55000   28
4      Eva         IT   80000   35

In [13]:
#group by department or split by department 
groups = df2.groupby("Department")
print(groups)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x10f035400>

In [14]:
# Apply any operation on it  and combine it 
df2.groupby("Department")["Salary"].mean()

Department
HR    52500.0
IT    80000.0
Name: Salary, dtype: float64

Aggregate Multiple Coloumn With Multiple Function(Grouped)

In [16]:
result = df2.groupby("Department").agg({
    "Salary": ["sum", "mean", "max"],
    "Age": ["min", "max", "mean"]
})

result

            Salary                 Age
               sum     mean    max min max  mean
Department
HR          105000  52500.0  55000  25  28  26.5
IT          240000  80000.0  90000  22  35  29.0


merge()	-> Combine DataFrames based on common columns or keys--JOIN
concat() -> Stack DataFrames vertically or horizontally. --	UNION / column binding
join()	-> Join DataFrames using their indexes (or a key) --	JOIN

In [20]:
df3 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"]
})

df4 = pd.DataFrame({
    "ID": [1, 2, 4],
    "Salary": [50000, 60000, 70000]
})

result = pd.merge(df3, df4, on="ID", how="inner")
print(result)

   ID   Name  Salary
0   1  Alice   50000
1   2    Bob   60000

Merge Types

In [23]:
pd.merge(df3, df4, on="ID", how="inner")   # Common rows
pd.merge(df3, df4, on="ID", how="left")    # All rows from left
pd.merge(df3, df4, on="ID", how="right")   # All rows from right
pd.merge(df3, df4, on="ID", how="outer")   # All rows from both

   ID     Name   Salary
0   1    Alice  50000.0
1   2      Bob  60000.0
2   3  Charlie      NaN
3   4      NaN  70000.0

In [28]:
df5 = pd.DataFrame({
    "Date": [
        "2024-01-01", "2024-01-02", "2024-01-03", "2024-01-04",
        "2024-01-05", "2024-01-06", "2024-01-07", "2024-01-08",
        "2024-01-09", "2024-01-10"
    ],
    "Product": [
        "Laptop", "Phone", "Tablet", "Monitor", "Keyboard",
        "Mouse", "Laptop", "Phone", "Tablet", "Monitor"
    ],
    "Region": [
        "North", "South", "East", "West", "North",
        "South", "East", "West", "North", "South"
    ],
    "Sales": [
        1200, 800, 600, 450, 150,
        100, 1800, 950, 700, 550
    ],
    "Units": [
        2, 4, 3, 5, 10,
        12, 3, 5, 4, 6
    ],
    "Rep": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan",
        "Alice", "Bob", "Charlie", "Diana", "Ethan"
    ]
})


print(df5)

         Date   Product Region  Sales  Units      Rep
0  2024-01-01    Laptop  North   1200      2    Alice
1  2024-01-02     Phone  South    800      4      Bob
2  2024-01-03    Tablet   East    600      3  Charlie
3  2024-01-04   Monitor   West    450      5    Diana
4  2024-01-05  Keyboard  North    150     10    Ethan
5  2024-01-06     Mouse  South    100     12    Alice
6  2024-01-07    Laptop   East   1800      3      Bob
7  2024-01-08     Phone   West    950      5  Charlie
8  2024-01-09    Tablet  North    700      4    Diana
9  2024-01-10   Monitor  South    550      6    Ethan